# Generated by Django 5.0.7 on 2024-07-10 13:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0003_censorinfo_director_movie_censor_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='directed_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='directed_movies', to='movie.director'),
        ),
    ]
